#!/bin/bash

trap ctrl_c INT

file_name=$1
op="${file_name%.*}"

function ctrl_c(){
    if [ -f $op ]; then
        rm -rf $op
        echo -e "\n"
    fi 
    exit 0 
}

g++ -std=c++14 $file_name -o $op

NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'

if [ -f $op ]; then
    echo -e "${GREEN}====================COMPILE SUCCESS===========================${NC}"
    ./$op
    rm -rf $op
else
    echo -e "${RED}====================COMPILE ERROR===========================${NC}"
fi
 
exit 0
